# Generated by Django 5.1.2 on 2024-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'HR'), ('Engineering', 'Engineering'), ('Sales', 'Sales')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst')], max_length=50, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
